### ISSUE TITLE
sub-directories

### ISSUE THREAD

**Issue by michael-ames** [jb-delafosse/linky-note#231]
I've got this installed and it's working well for files in a single/top-level directory that I can call by name/extension:
`[link text](filename.md)`

But it doesn't seem to be able to handle relative paths for sub/super-directories, like [](../filename.md) or [](recipes/filename.md). 

This might be by design, but it'd certainly be useful if this could find links to non-sibling files.

**Comment by jb-delafosse** [comment]
Done. I need to add some End to end tests before releasing it.
